# -*- coding: utf-8 -*-
"""ejercicio2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XOuZ8kP7YhaNIaQixDKVOaZbz2PEaW-z
"""

import numpy as np
import matplotlib.pyplot as plt

#Los parámetros
alpha = 2.0
beta = 1.0
KB = 1.0
n = 2.0

def g_R(x):
  # Modified to handle x=0 to prevent ZeroDivisionError.
  # This is a common form for a Hill repression function.
  return 1 / (1 + (x/KB)**n)

def gillespie_simulation(Omega, t_max=1000, r1_init=None, r2_init=0):
  #Inicializacion
  if r1_init is None:
    r1_init = 2 * Omega

  r1 = r1_init
  r2 = r2_init
  t = 0.0
  times = [t]
  r1_traj = [r1]
  r2_traj = [r2]

  while t < t_max:
    #Propensidades
    nu1 = alpha * g_R(r2 / Omega)
    nu2 = alpha * g_R(r1 / Omega)
    nu3 = beta * r1 / Omega
    nu4 = beta * r2 / Omega
    nu_total = nu1 + nu2 + nu3 + nu4

    if nu_total == 0:
      break

    #Tiempo de la proxima reacción
    dt = np.random.exponential(1/nu_total)
    t += dt

    #Eleccion de reacción(ruleta)
    rand = np.random.uniform(0, nu_total)
    if rand < nu1:
      r1 += 1 #síntesis r1
    elif rand < nu1 + nu2:
      r2 += 1 #síntesis r2
    elif rand < nu1 + nu2 + nu3:
      if r1 > 0: r1 -= 1 #Degradación
    elif rand < nu1 + nu2 + nu3 + nu4:
      if r2 > 0: r2 -= 1 #Degradación

    times.append(t)
    r1_traj.append(r1)
    r2_traj.append(r2)

  return times, r1_traj, r2_traj


#simulación de diferentes Omegas
Omegas = [1, 10, 1000]
for Omega in Omegas:
  times, r1_traj, r2_traj = gillespie_simulation(Omega)


  #Grafica de la trayectoria
  plt.figure()
  plt.plot(times, np.array(r1_traj)/Omega, label = 'x1 = r1/Omega')
  plt.plot(times, np.array(r2_traj)/Omega, label = 'x2 = r2/Omega')
  plt.xlabel('TIempo')
  plt.ylabel('Concentración')
  plt.title(f'Omega = {Omega}')
  plt.legend()
  plt.show()



  #Switching: si r2 > r1 al final o en algún punto cruza

  if any(np.array(r2_traj) > np.array(r1_traj)):
    print(f'Omega = {Omega}: switching espontáneo')
  else:
    print(f'Omega = {Omega}: no switching espontáneo')